# Use the micromamba base image
FROM mambaorg/micromamba:2-ubuntu22.04

LABEL author="Ben C"
LABEL version="1.0"
LABEL description="Micromamba-based container for CNV-Caller ETL processes (compiling pfb, formatting output tables and joins)"

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        procps \
        build-essential \
        curl \
    && apt-get clean && \
    rm -rf /var/lib/apt/lists/*


# Install Python packages with micromamba
RUN micromamba install -y -n base -c conda-forge \
        python=3.11 \
        polars \
        duckdb \
        psutil \
        pandas \
        matplotlib \
        tqdm && \
    micromamba clean --all --yes

# Set environment variables
ENV MAMBA_ROOT_PREFIX=/opt/conda
ENV PATH=$MAMBA_ROOT_PREFIX/bin:$PATH


# Default shell
CMD ["bash"]
